# Generated by Django 2.2.4 on 2019-10-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=50)),
                ('title_2', models.CharField(max_length=50)),
                ('image_url_1', models.TextField()),
                ('image_url_2', models.TextField()),
            ],
        ),
    ]
